// Code generated by "stringer -type ChecksumScheme"; DO NOT EDIT

package sardata

import "fmt"

const _ChecksumScheme_name = "ChecksumSHA2_256ChecksumSHA2_512ChecksumBLAKE2sChecksumBLAKE2bChecksumSHA3_256ChecksumSHA3_512"

var _ChecksumScheme_index = [...]uint8{0, 16, 32, 47, 62, 78, 94}

func (i ChecksumScheme) String() string {
	i -= 1
	if i >= ChecksumScheme(len(_ChecksumScheme_index)-1) {
		return fmt.Sprintf("ChecksumScheme(%d)", i+1)
	}
	return _ChecksumScheme_name[_ChecksumScheme_index[i]:_ChecksumScheme_index[i+1]]
}
