# Copyright (c) 2017 Robert Iannucci Jr. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

language: go

go:
- 1.7

before_install:
  - wget https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip /tmp/protoc.zip
  - mkdir /tmp/protoc
  - cd /tmp/protoc && unzip ../protoc.zip
  - export PATH=$PATH:/tmp/protoc/bin
  - go get github.com/golang/protobuf/protoc-gen-go
  - go get github.com/maruel/pre-commit-go/cmd/pcg

script:
  - pcg -C 16
